/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classlar;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asimk
 */
public class KullaniciDuzenle extends javax.swing.JFrame {

    /**
     * Creates new form PersonelDuzenle
     */
    Kullanici k1;
    String type;
    public void bilgigoster(){
        txtIsim.setText(k1.getAd());
        txtYas.setText(String.valueOf(k1.getYas()));
        txtTel.setText(k1.getTelefon());
        txtMail.setText(k1.getMail());
        txtCinsiyet.setText(k1.getCinsiyet());
        txtTCKN.setText(k1.getTcKimlik());
        DefaultTableModel m = (DefaultTableModel) tblKredi.getModel();
        m.setRowCount(0);
        try {
            if(type.equals("Müşteri")){
                ArrayList<Object[]> hesaplar2 = ((Musteri) k1).logCek();
                for (int i = 0; i < hesaplar2.size(); i++) {
                    m.addRow(hesaplar2.get(i));
                }
            }
            else{
                ArrayList<Object[]> hesaplar2 = ((Calisan) k1).logCek();
                for (int i = 0; i < hesaplar2.size(); i++) {
                    m.addRow(hesaplar2.get(i));
                }
            }
            
        } catch (Exception e) {
        }
        setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
    public KullaniciDuzenle(Kullanici k1,String type) {
        initComponents();
        this.k1 = k1;
        this.type = type;
        bilgigoster();
        tblKredi.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblKredi.getTableHeader().setOpaque(false);
        tblKredi.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblKredi.getTableHeader().setForeground(new Color(255, 255, 255));
        tblKredi.setRowHeight(25);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKredi = new javax.swing.JTable();
        txtTell = new javax.swing.JLabel();
        txtCinsiyett = new javax.swing.JLabel();
        txtYass = new javax.swing.JLabel();
        txtIsimm = new javax.swing.JLabel();
        txtTCKNN = new javax.swing.JLabel();
        txtMaill = new javax.swing.JLabel();
        txtMail1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtIsim = new javax.swing.JTextField();
        txtYas = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtCinsiyet = new javax.swing.JTextField();
        txtTCKN = new javax.swing.JTextField();
        btnYoneticiKendiProfil2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 26, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKredi.setBackground(java.awt.Color.white);
        tblKredi.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tblKredi.setForeground(new java.awt.Color(20, 26, 54));
        tblKredi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NO", "İşlem Açıklaması"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKredi.setFocusable(false);
        tblKredi.setGridColor(java.awt.Color.white);
        tblKredi.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKredi.setOpaque(false);
        tblKredi.setRowHeight(25);
        tblKredi.setSelectionBackground(new java.awt.Color(20, 11, 32));
        tblKredi.setSelectionForeground(java.awt.Color.white);
        tblKredi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKredi.getTableHeader().setReorderingAllowed(false);
        tblKredi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tblKrediAncestorRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(tblKredi);
        if (tblKredi.getColumnModel().getColumnCount() > 0) {
            tblKredi.getColumnModel().getColumn(0).setMinWidth(25);
            tblKredi.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblKredi.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 950, 320));

        txtTell.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtTell.setForeground(new java.awt.Color(255, 255, 255));
        txtTell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/HesapDetay/phone.png"))); // NOI18N
        txtTell.setToolTipText("");
        jPanel1.add(txtTell, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, -1));

        txtCinsiyett.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtCinsiyett.setForeground(new java.awt.Color(255, 255, 255));
        txtCinsiyett.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCinsiyett.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/HesapDetay/gender.png"))); // NOI18N
        txtCinsiyett.setToolTipText("");
        jPanel1.add(txtCinsiyett, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtYass.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtYass.setForeground(new java.awt.Color(255, 255, 255));
        txtYass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtYass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/HesapDetay/birthday.png"))); // NOI18N
        txtYass.setToolTipText("");
        jPanel1.add(txtYass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtIsimm.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtIsimm.setForeground(new java.awt.Color(255, 255, 255));
        txtIsimm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtIsimm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/HesapDetay/user.png"))); // NOI18N
        txtIsimm.setToolTipText("");
        jPanel1.add(txtIsimm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtTCKNN.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtTCKNN.setForeground(new java.awt.Color(255, 255, 255));
        txtTCKNN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTCKNN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/HesapDetay/id.png"))); // NOI18N
        txtTCKNN.setToolTipText("");
        jPanel1.add(txtTCKNN, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 30, -1));

        txtMaill.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtMaill.setForeground(new java.awt.Color(255, 255, 255));
        txtMaill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMaill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/HesapDetay/mail.png"))); // NOI18N
        txtMaill.setToolTipText("");
        jPanel1.add(txtMaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 30, -1));

        txtMail1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtMail1.setForeground(new java.awt.Color(255, 255, 255));
        txtMail1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/HesapDetay/mail.png"))); // NOI18N
        txtMail1.setToolTipText("");
        jPanel1.add(txtMail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 40, -1));

        txtMail.setBackground(new java.awt.Color(27, 41, 86));
        txtMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMail.setForeground(new java.awt.Color(255, 255, 255));
        txtMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 320, 40));

        txtIsim.setBackground(new java.awt.Color(27, 41, 86));
        txtIsim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIsim.setForeground(new java.awt.Color(255, 255, 255));
        txtIsim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIsim.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtIsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 320, 40));

        txtYas.setEditable(false);
        txtYas.setBackground(new java.awt.Color(27, 41, 86));
        txtYas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtYas.setForeground(new java.awt.Color(255, 255, 255));
        txtYas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtYas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtYas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 320, 40));

        txtTel.setBackground(new java.awt.Color(27, 41, 86));
        txtTel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTel.setForeground(new java.awt.Color(255, 255, 255));
        txtTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 320, 40));

        txtCinsiyet.setEditable(false);
        txtCinsiyet.setBackground(new java.awt.Color(27, 41, 86));
        txtCinsiyet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCinsiyet.setForeground(new java.awt.Color(255, 255, 255));
        txtCinsiyet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCinsiyet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtCinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 320, 40));

        txtTCKN.setBackground(new java.awt.Color(27, 41, 86));
        txtTCKN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTCKN.setForeground(new java.awt.Color(255, 255, 255));
        txtTCKN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTCKN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTCKN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 320, 40));

        btnYoneticiKendiProfil2.setBackground(java.awt.Color.white);
        btnYoneticiKendiProfil2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnYoneticiKendiProfil2.setForeground(java.awt.Color.blue);
        btnYoneticiKendiProfil2.setText("KAYDET");
        btnYoneticiKendiProfil2.setOpaque(false);
        btnYoneticiKendiProfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoneticiKendiProfil2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnYoneticiKendiProfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKrediAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblKrediAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKrediAncestorRemoved

    private void btnYoneticiKendiProfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoneticiKendiProfil2ActionPerformed
        // TODO add your handling code here:
        if(Yonetici.kullaniciDuzenle(k1, txtIsim.getText(), txtTel.getText(), txtMail.getText(), txtTCKN.getText())){
            JOptionPane.showMessageDialog(null, "Bilgiler kaydedildi. Lütfen pencere ekranından Güncelle butonuna basınız.");
            
            this.dispose();
        }
    }//GEN-LAST:event_btnYoneticiKendiProfil2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciDuzenle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYoneticiKendiProfil2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKredi;
    private javax.swing.JTextField txtCinsiyet;
    private javax.swing.JLabel txtCinsiyett;
    private javax.swing.JTextField txtIsim;
    private javax.swing.JLabel txtIsimm;
    private javax.swing.JTextField txtMail;
    private javax.swing.JLabel txtMail1;
    private javax.swing.JLabel txtMaill;
    private javax.swing.JTextField txtTCKN;
    private javax.swing.JLabel txtTCKNN;
    private javax.swing.JTextField txtTel;
    private javax.swing.JLabel txtTell;
    private javax.swing.JTextField txtYas;
    private javax.swing.JLabel txtYass;
    // End of variables declaration//GEN-END:variables
}
