/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classlar;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author asimk
 */
class SadeceRakam implements KeyListener {

  //bir önceki derste yaptigimiz tab menu sinifinda herhangi bir text alanina bu maskelemeyi yapacagimizdan bu sinifin nesnesini türettik

    public void keyTyped(KeyEvent e) {
        char caracter = e.getKeyChar();//hangi tusa basildigini okuyoruz
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {// bu if sart kontrolünde sadece 0 ile 9 arasinda rakamlarin girilebilecegini belirtiyoruz

            e.consume();
        }
    }

    public void keyPressed(KeyEvent e) {//tusa basildiginda aktif olur.
    }

    public void keyReleased(KeyEvent e) {//tus birakildiginda aktiflesir.
    }
}
class VirgulBlock implements KeyListener {

  //bir önceki derste yaptigimiz tab menu sinifinda herhangi bir text alanina bu maskelemeyi yapacagimizdan bu sinifin nesnesini türettik
    
    public void keyTyped(KeyEvent e) {
        char caracter = e.getKeyChar();//hangi tusa basildigini okuyoruz
        int key = e.getKeyCode();
        if (((caracter ==',') || (key ==  KeyEvent.VK_TAB)) && (caracter != '\b')) {// bu if sart kontrolünde sadece karakter alıyoruz.

            e.consume();
        }
    }

    public void keyPressed(KeyEvent e) {//tusa basildiginda aktif olur.
    }

    public void keyReleased(KeyEvent e) {//tus birakildiginda aktiflesir.
    }
}
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Kullanici i1;
    public Login() {
        
        initComponents();
        pnlKayitOl.setVisible(false);
        pnlSifremiUnuttum.setVisible(false);
        pnlGirisYap.setVisible(true);
        setLocationRelativeTo(null);
        txtUserNo.addKeyListener(new VirgulBlock());
        txtUserParola.addKeyListener(new VirgulBlock());
        txtPersonelNo.addKeyListener(new VirgulBlock());
        txtPersonelParola.addKeyListener(new VirgulBlock());
        txtYoneticiNo.addKeyListener(new VirgulBlock());
        txtYoneticiParola.addKeyListener(new VirgulBlock());
        txtKayitAd.addKeyListener(new VirgulBlock());
        txtKayitSoyad.addKeyListener(new VirgulBlock());
        txtKayitTCKN.addKeyListener(new SadeceRakam());
        txtKayitYas.addKeyListener(new SadeceRakam());
        txtKayitMail.addKeyListener(new VirgulBlock());
        txtKayitParola.addKeyListener(new VirgulBlock());
        txtKayitTelefon.addKeyListener(new SadeceRakam());
        txtUserNo.setFocusTraversalKeysEnabled(false);
        txtUserParola.setFocusTraversalKeysEnabled(false);
        txtPersonelNo.setFocusTraversalKeysEnabled(false);
        txtPersonelParola.setFocusTraversalKeysEnabled(false);
        txtYoneticiNo.setFocusTraversalKeysEnabled(false);
        txtYoneticiParola.setFocusTraversalKeysEnabled(false);
        txtKayitAd.setFocusTraversalKeysEnabled(false);
        txtKayitSoyad.setFocusTraversalKeysEnabled(false);
        txtKayitTCKN.setFocusTraversalKeysEnabled(false);
        txtKayitYas.setFocusTraversalKeysEnabled(false);
        txtKayitMail.setFocusTraversalKeysEnabled(false);
        txtKayitParola.setFocusTraversalKeysEnabled(false);
        txtKayitTelefon.setFocusTraversalKeysEnabled(false);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinsiyet = new javax.swing.ButtonGroup();
        pnlGirisYap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnYonetici = new javax.swing.JLabel();
        btnUser = new javax.swing.JLabel();
        btnPersonel = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtUserNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUserParola = new javax.swing.JPasswordField();
        pnlPersonel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtPersonelNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPersonelParola = new javax.swing.JPasswordField();
        pnlYonetici = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtYoneticiNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtYoneticiParola = new javax.swing.JPasswordField();
        btnUserLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlKayitOl = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnKayitOl = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnYoneticiKayit = new javax.swing.JLabel();
        btnUserKayit = new javax.swing.JLabel();
        btnPersonelKayit = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtKayitYas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtKayitAd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtKayitSoyad = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtKayitTCKN = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtKayitTelefon = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        txtKayitMail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtKayitKullanici = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtKayitParola = new javax.swing.JPasswordField();
        jLabel29 = new javax.swing.JLabel();
        pnlSifremiUnuttum = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnUserLogin2 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtSifremiUnuttum = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnYoneticiSifremiUnuttum = new javax.swing.JLabel();
        btnUserSifremiUnuttum = new javax.swing.JLabel();
        btnPersonelSifremiUnuttum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Yap");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGirisYap.setBackground(new java.awt.Color(10, 25, 74));
        pnlGirisYap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/login/login-bottom.png"))); // NOI18N
        pnlGirisYap.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buradan Giriş Yapabilirsin");
        pnlGirisYap.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, 40));

        jLabel4.setBackground(new java.awt.Color(157, 176, 242));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(157, 176, 242));
        jLabel4.setText("Lütfen seçeneklerden birini seç ve bilgilerini gir");
        pnlGirisYap.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 30));

        jLabel6.setBackground(new java.awt.Color(157, 176, 242));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(157, 176, 242));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/login/right-arrow.png"))); // NOI18N
        jLabel6.setText("Kayıt Ol ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        pnlGirisYap.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, 40));

        jPanel2.setBackground(new java.awt.Color(10, 25, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnYonetici.setBackground(new java.awt.Color(10, 25, 74));
        btnYonetici.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnYonetici.setForeground(new java.awt.Color(204, 204, 204));
        btnYonetici.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnYonetici.setText("YÖNETİCİ");
        btnYonetici.setOpaque(true);
        btnYonetici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnYoneticiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnYoneticiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnYoneticiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnYoneticiMouseReleased(evt);
            }
        });
        jPanel2.add(btnYonetici, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 30));

        btnUser.setBackground(new java.awt.Color(204, 204, 204));
        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUser.setForeground(new java.awt.Color(10, 25, 74));
        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUser.setText("MÜŞTERİ");
        btnUser.setOpaque(true);
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUserMouseReleased(evt);
            }
        });
        jPanel2.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        btnPersonel.setBackground(new java.awt.Color(10, 25, 74));
        btnPersonel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnPersonel.setForeground(new java.awt.Color(204, 204, 204));
        btnPersonel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPersonel.setText("PERSONEL");
        btnPersonel.setOpaque(true);
        btnPersonel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPersonelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPersonelMouseReleased(evt);
            }
        });
        jPanel2.add(btnPersonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 30));

        pnlGirisYap.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 280, 50));

        pnlUser.setBackground(new java.awt.Color(10, 25, 74));
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(157, 176, 242));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(157, 176, 242));
        jLabel7.setText("Müşteri No");
        pnlUser.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        txtUserNo.setBackground(new java.awt.Color(27, 41, 86));
        txtUserNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserNo.setForeground(new java.awt.Color(255, 255, 255));
        txtUserNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtUserNo.setOpaque(false);
        txtUserNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNoKeyTyped(evt);
            }
        });
        pnlUser.add(txtUserNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 40));

        jLabel5.setBackground(new java.awt.Color(157, 176, 242));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(157, 176, 242));
        jLabel5.setText("Parola");
        pnlUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        txtUserParola.setBackground(new java.awt.Color(27, 41, 86));
        txtUserParola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserParola.setForeground(new java.awt.Color(255, 255, 255));
        txtUserParola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserParola.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtUserParola.setOpaque(false);
        pnlUser.add(txtUserParola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 40));

        pnlGirisYap.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 300, 170));

        pnlPersonel.setBackground(new java.awt.Color(10, 25, 74));
        pnlPersonel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(157, 176, 242));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(157, 176, 242));
        jLabel8.setText("Personel No");
        pnlPersonel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        txtPersonelNo.setBackground(new java.awt.Color(27, 41, 86));
        txtPersonelNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPersonelNo.setForeground(new java.awt.Color(255, 255, 255));
        txtPersonelNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonelNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtPersonelNo.setOpaque(false);
        pnlPersonel.add(txtPersonelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 40));

        jLabel9.setBackground(new java.awt.Color(157, 176, 242));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(157, 176, 242));
        jLabel9.setText("Parola");
        pnlPersonel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        txtPersonelParola.setBackground(new java.awt.Color(27, 41, 86));
        txtPersonelParola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPersonelParola.setForeground(new java.awt.Color(255, 255, 255));
        txtPersonelParola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonelParola.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtPersonelParola.setOpaque(false);
        pnlPersonel.add(txtPersonelParola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 40));

        pnlGirisYap.add(pnlPersonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 300, 170));

        pnlYonetici.setBackground(new java.awt.Color(10, 25, 74));
        pnlYonetici.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(157, 176, 242));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(157, 176, 242));
        jLabel11.setText("Yönetici No");
        pnlYonetici.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        txtYoneticiNo.setBackground(new java.awt.Color(27, 41, 86));
        txtYoneticiNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtYoneticiNo.setForeground(new java.awt.Color(255, 255, 255));
        txtYoneticiNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtYoneticiNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtYoneticiNo.setOpaque(false);
        pnlYonetici.add(txtYoneticiNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 40));

        jLabel12.setBackground(new java.awt.Color(157, 176, 242));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(157, 176, 242));
        jLabel12.setText("Parola");
        pnlYonetici.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        txtYoneticiParola.setBackground(new java.awt.Color(27, 41, 86));
        txtYoneticiParola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtYoneticiParola.setForeground(new java.awt.Color(255, 255, 255));
        txtYoneticiParola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtYoneticiParola.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtYoneticiParola.setOpaque(false);
        pnlYonetici.add(txtYoneticiParola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 40));

        pnlGirisYap.add(pnlYonetici, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 300, 170));

        btnUserLogin.setBackground(new java.awt.Color(114, 54, 251));
        btnUserLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUserLogin.setForeground(java.awt.Color.white);
        btnUserLogin.setText("GİRİŞ YAP");
        btnUserLogin.setBorder(new javax.swing.border.MatteBorder(null));
        btnUserLogin.setOpaque(false);
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });
        pnlGirisYap.add(btnUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 280, 40));

        jLabel2.setBackground(new java.awt.Color(157, 176, 242));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 108, 118));
        jLabel2.setText("Şifreni mi unuttun?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        pnlGirisYap.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        getContentPane().add(pnlGirisYap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 585));

        pnlKayitOl.setBackground(new java.awt.Color(10, 25, 74));
        pnlKayitOl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(157, 176, 242));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(157, 176, 242));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/login/right-arrow.png"))); // NOI18N
        jLabel13.setText("Giriş Yap");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        pnlKayitOl.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, 40));

        btnKayitOl.setBackground(new java.awt.Color(114, 54, 251));
        btnKayitOl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKayitOl.setForeground(new java.awt.Color(204, 204, 204));
        btnKayitOl.setText("KAYIT OL");
        btnKayitOl.setBorder(new javax.swing.border.MatteBorder(null));
        btnKayitOl.setOpaque(false);
        btnKayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitOlActionPerformed(evt);
            }
        });
        pnlKayitOl.add(btnKayitOl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 280, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/login/login-bottom.png"))); // NOI18N
        pnlKayitOl.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buradan Kayıt Olabilirsin");
        pnlKayitOl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 40));

        jPanel3.setBackground(new java.awt.Color(10, 25, 74));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnYoneticiKayit.setBackground(new java.awt.Color(10, 25, 74));
        btnYoneticiKayit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnYoneticiKayit.setForeground(new java.awt.Color(204, 204, 204));
        btnYoneticiKayit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnYoneticiKayit.setText("YÖNETİCİ");
        btnYoneticiKayit.setOpaque(true);
        btnYoneticiKayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnYoneticiKayitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnYoneticiKayitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnYoneticiKayitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnYoneticiKayitMouseReleased(evt);
            }
        });
        jPanel3.add(btnYoneticiKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 30));

        btnUserKayit.setBackground(new java.awt.Color(204, 204, 204));
        btnUserKayit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUserKayit.setForeground(new java.awt.Color(10, 25, 74));
        btnUserKayit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUserKayit.setText("MÜŞTERİ");
        btnUserKayit.setOpaque(true);
        btnUserKayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserKayitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserKayitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserKayitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUserKayitMouseReleased(evt);
            }
        });
        jPanel3.add(btnUserKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        btnPersonelKayit.setBackground(new java.awt.Color(10, 25, 74));
        btnPersonelKayit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnPersonelKayit.setForeground(new java.awt.Color(204, 204, 204));
        btnPersonelKayit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPersonelKayit.setText("PERSONEL");
        btnPersonelKayit.setOpaque(true);
        btnPersonelKayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonelKayitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonelKayitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPersonelKayitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPersonelKayitMouseReleased(evt);
            }
        });
        jPanel3.add(btnPersonelKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 30));

        pnlKayitOl.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 280, 50));

        jLabel17.setBackground(new java.awt.Color(157, 176, 242));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(157, 176, 242));
        jLabel17.setText("Kullanıcı Tipi");
        pnlKayitOl.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        txtKayitYas.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitYas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitYas.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitYas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitYas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtKayitYas.setOpaque(false);
        txtKayitYas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKayitYasMouseReleased(evt);
            }
        });
        pnlKayitOl.add(txtKayitYas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, 40));

        jLabel18.setBackground(new java.awt.Color(157, 176, 242));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(157, 176, 242));
        jLabel18.setText("Doğum Tarihi");
        pnlKayitOl.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, 20));

        txtKayitAd.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitAd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitAd.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitAd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitAd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlKayitOl.add(txtKayitAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 280, 40));

        jLabel16.setBackground(new java.awt.Color(157, 176, 242));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(157, 176, 242));
        jLabel16.setText("Ad");
        pnlKayitOl.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel19.setBackground(new java.awt.Color(157, 176, 242));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(157, 176, 242));
        jLabel19.setText("Soyad");
        pnlKayitOl.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabel20.setBackground(new java.awt.Color(157, 176, 242));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(157, 176, 242));
        jLabel20.setText("Yaş");
        pnlKayitOl.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));

        txtKayitSoyad.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitSoyad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitSoyad.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitSoyad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitSoyad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtKayitSoyad.setOpaque(false);
        txtKayitSoyad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKayitSoyadMouseReleased(evt);
            }
        });
        pnlKayitOl.add(txtKayitSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 280, 40));

        jComboBox1.setBackground(new java.awt.Color(27, 41, 86));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yıl", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jComboBox1.setOpaque(false);
        pnlKayitOl.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, 40));

        jComboBox2.setBackground(new java.awt.Color(27, 41, 86));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gün", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jComboBox2.setOpaque(false);
        pnlKayitOl.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 60, 40));

        jComboBox3.setBackground(new java.awt.Color(27, 41, 86));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ay", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        jComboBox3.setOpaque(false);
        pnlKayitOl.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 60, 40));

        jLabel21.setBackground(new java.awt.Color(157, 176, 242));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(157, 176, 242));
        jLabel21.setText("Cinsiyet");
        pnlKayitOl.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, 20));

        txtKayitTCKN.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitTCKN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitTCKN.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitTCKN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitTCKN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtKayitTCKN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKayitTCKNMouseReleased(evt);
            }
        });
        pnlKayitOl.add(txtKayitTCKN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 280, 40));

        jLabel22.setBackground(new java.awt.Color(157, 176, 242));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(157, 176, 242));
        jLabel22.setText("Telefon Numarası");
        pnlKayitOl.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 20));

        txtKayitTelefon.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitTelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitTelefon.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitTelefon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitTelefon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtKayitTelefon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKayitTelefonMouseReleased(evt);
            }
        });
        pnlKayitOl.add(txtKayitTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 280, 40));

        jLabel23.setBackground(new java.awt.Color(157, 176, 242));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(157, 176, 242));
        jLabel23.setText("TC Kimlik Numarası");
        pnlKayitOl.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));

        jRadioButton1.setBackground(new java.awt.Color(10, 25, 74));
        cinsiyet.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setForeground(java.awt.Color.white);
        jRadioButton1.setText("Kadın");
        jRadioButton1.setOpaque(false);
        pnlKayitOl.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, 40));

        jRadioButton2.setBackground(new java.awt.Color(10, 25, 74));
        cinsiyet.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setForeground(java.awt.Color.white);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Erkek");
        jRadioButton2.setOpaque(false);
        pnlKayitOl.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, 40));

        jLabel24.setBackground(new java.awt.Color(157, 176, 242));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(157, 176, 242));
        jLabel24.setText("Mail Adresi");
        pnlKayitOl.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, 20));

        txtKayitMail.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitMail.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitMail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtKayitMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKayitMailMouseReleased(evt);
            }
        });
        pnlKayitOl.add(txtKayitMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 280, 40));

        jLabel25.setBackground(new java.awt.Color(157, 176, 242));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(157, 176, 242));
        jLabel25.setText("Parola");
        pnlKayitOl.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, 20));

        txtKayitKullanici.setEditable(false);
        txtKayitKullanici.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitKullanici.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitKullanici.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitKullanici.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitKullanici.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlKayitOl.add(txtKayitKullanici, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 280, 40));

        jLabel26.setBackground(new java.awt.Color(157, 176, 242));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(157, 176, 242));
        jLabel26.setText("Müşteri No");
        pnlKayitOl.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, 20));

        txtKayitParola.setBackground(new java.awt.Color(27, 41, 86));
        txtKayitParola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKayitParola.setForeground(new java.awt.Color(255, 255, 255));
        txtKayitParola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKayitParola.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtKayitParola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKayitParolaMouseReleased(evt);
            }
        });
        pnlKayitOl.add(txtKayitParola, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 280, 40));

        jLabel29.setBackground(new java.awt.Color(157, 176, 242));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(157, 176, 242));
        jLabel29.setText("Lütfen seçeneklerden birini seçip gerekli alanları doldur");
        pnlKayitOl.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        getContentPane().add(pnlKayitOl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 585));

        pnlSifremiUnuttum.setBackground(new java.awt.Color(10, 25, 74));
        pnlSifremiUnuttum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/login/login-bottom.png"))); // NOI18N
        pnlSifremiUnuttum.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Buradan Şifreni Öğrenebilirsin");
        pnlSifremiUnuttum.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, 40));

        jLabel30.setBackground(new java.awt.Color(157, 176, 242));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(157, 176, 242));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classlar/ui/login/right-arrow.png"))); // NOI18N
        jLabel30.setText("Giriş Yap ");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel30MousePressed(evt);
            }
        });
        pnlSifremiUnuttum.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, 40));

        btnUserLogin2.setBackground(new java.awt.Color(114, 54, 251));
        btnUserLogin2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUserLogin2.setForeground(new java.awt.Color(204, 204, 204));
        btnUserLogin2.setText("PAROLAMI GÖSTER");
        btnUserLogin2.setBorder(new javax.swing.border.MatteBorder(null));
        btnUserLogin2.setOpaque(false);
        btnUserLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLogin2ActionPerformed(evt);
            }
        });
        pnlSifremiUnuttum.add(btnUserLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 280, 40));

        jLabel32.setBackground(new java.awt.Color(157, 176, 242));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(157, 176, 242));
        jLabel32.setText("Lütfen Kullanıcı Tipini Seç ve Mail Adresini Gir");
        pnlSifremiUnuttum.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 30));

        jLabel31.setBackground(new java.awt.Color(157, 176, 242));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(157, 176, 242));
        jLabel31.setText("Mail Adresi");
        pnlSifremiUnuttum.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, 20));

        txtSifremiUnuttum.setBackground(new java.awt.Color(27, 41, 86));
        txtSifremiUnuttum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSifremiUnuttum.setForeground(new java.awt.Color(255, 255, 255));
        txtSifremiUnuttum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSifremiUnuttum.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 2, 0, new java.awt.Color(0, 0, 0)));
        txtSifremiUnuttum.setOpaque(false);
        pnlSifremiUnuttum.add(txtSifremiUnuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 280, 40));

        jPanel4.setBackground(new java.awt.Color(10, 25, 74));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(10, 25, 74));
        btnYoneticiSifremiUnuttum.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(204, 204, 204));
        btnYoneticiSifremiUnuttum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnYoneticiSifremiUnuttum.setText("YÖNETİCİ");
        btnYoneticiSifremiUnuttum.setOpaque(true);
        btnYoneticiSifremiUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnYoneticiSifremiUnuttumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnYoneticiSifremiUnuttumMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnYoneticiSifremiUnuttumMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnYoneticiSifremiUnuttumMouseReleased(evt);
            }
        });
        jPanel4.add(btnYoneticiSifremiUnuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 30));

        btnUserSifremiUnuttum.setBackground(new java.awt.Color(204, 204, 204));
        btnUserSifremiUnuttum.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUserSifremiUnuttum.setForeground(new java.awt.Color(10, 25, 74));
        btnUserSifremiUnuttum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUserSifremiUnuttum.setText("MÜŞTERİ");
        btnUserSifremiUnuttum.setOpaque(true);
        btnUserSifremiUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserSifremiUnuttumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserSifremiUnuttumMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserSifremiUnuttumMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUserSifremiUnuttumMouseReleased(evt);
            }
        });
        jPanel4.add(btnUserSifremiUnuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(10, 25, 74));
        btnPersonelSifremiUnuttum.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(204, 204, 204));
        btnPersonelSifremiUnuttum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPersonelSifremiUnuttum.setText("PERSONEL");
        btnPersonelSifremiUnuttum.setOpaque(true);
        btnPersonelSifremiUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonelSifremiUnuttumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonelSifremiUnuttumMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPersonelSifremiUnuttumMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPersonelSifremiUnuttumMouseReleased(evt);
            }
        });
        jPanel4.add(btnPersonelSifremiUnuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 30));

        pnlSifremiUnuttum.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 280, 50));

        getContentPane().add(pnlSifremiUnuttum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 585));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean isUserOk = true,isPersonelOk =false, isYoneticiOk = false;
    
    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
         if(isUserOk== false){
             btnUser.setBackground(new java.awt.Color(51,35,119));
             btnUser.setForeground(new java.awt.Color(204,204,204));
         }
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMousePressed
        // TODO add your handling code here:
        if(isUserOk != true){
            btnUser.setBackground(new java.awt.Color(31,73,103));
             btnUser.setForeground(new java.awt.Color(10,25,74));
            isUserOk = true;
            isPersonelOk = false;
            isYoneticiOk = false;
            btnPersonel.setBackground(new java.awt.Color(10,25,74));
            btnPersonel.setForeground(new java.awt.Color(204,204,204));
            btnYonetici.setBackground(new java.awt.Color(10,25,74));
            btnYonetici.setForeground(new java.awt.Color(204,204,204));
            pnlUser.setVisible(true);
            pnlPersonel.setVisible(false);
            pnlYonetici.setVisible(false);
            
        }
    }//GEN-LAST:event_btnUserMousePressed

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        // TODO add your handling code here:
        if(isUserOk==true){
            btnUser.setBackground(new java.awt.Color(204,204,204));
             btnUser.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnUser.setBackground(new java.awt.Color(10,25,74));
             btnUser.setForeground(new java.awt.Color(204,204,204));
        }
      
    }//GEN-LAST:event_btnUserMouseExited

    private void btnUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseReleased
        // TODO add your handling code here:
        if(isUserOk==true){
            btnUser.setBackground(new java.awt.Color(204,204,204));
             btnUser.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnUser.setBackground(new java.awt.Color(10,25,74));
             btnUser.setForeground(new java.awt.Color(204,204,204));
        }
      
    }//GEN-LAST:event_btnUserMouseReleased

    private void btnPersonelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelMouseEntered
        // TODO add your handling code here:
        if(isPersonelOk== false){
             btnPersonel.setBackground(new java.awt.Color(51,35,119));
             btnPersonel.setForeground(new java.awt.Color(204,204,204));
         }
    }//GEN-LAST:event_btnPersonelMouseEntered

    private void btnPersonelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelMousePressed
        // TODO add your handling code here:
        if(isPersonelOk != true){
            btnPersonel.setBackground(new java.awt.Color(31,73,103));
            btnPersonel.setForeground(new java.awt.Color(10,25,74));
            isUserOk = false;
            isPersonelOk = true;
            isYoneticiOk = false;
            btnUser.setBackground(new java.awt.Color(10,25,74));
            btnUser.setForeground(new java.awt.Color(204,204,204));
            btnYonetici.setBackground(new java.awt.Color(10,25,74));
            btnYonetici.setForeground(new java.awt.Color(204,204,204));
            pnlUser.setVisible(false);
            pnlPersonel.setVisible(true);
            pnlYonetici.setVisible(false);
            
        }
    }//GEN-LAST:event_btnPersonelMousePressed

    private void btnPersonelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelMouseExited
        // TODO add your handling code here:
        if(isPersonelOk==true){
            btnPersonel.setBackground(new java.awt.Color(204,204,204));
             btnPersonel.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnPersonel.setBackground(new java.awt.Color(10,25,74));
             btnPersonel.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnPersonelMouseExited

    private void btnPersonelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelMouseReleased
        // TODO add your handling code here:
        if(isPersonelOk==true){
            btnPersonel.setBackground(new java.awt.Color(204,204,204));
             btnPersonel.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnPersonel.setBackground(new java.awt.Color(10,25,74));
             btnPersonel.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnPersonelMouseReleased

    private void btnYoneticiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiMouseEntered
        // TODO add your handling code here:
        if(isYoneticiOk== false){
             btnYonetici.setBackground(new java.awt.Color(51,35,119));
             btnYonetici.setForeground(new java.awt.Color(204,204,204));
         }
    }//GEN-LAST:event_btnYoneticiMouseEntered

    private void btnYoneticiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiMousePressed
        // TODO add your handling code here:
        if(isYoneticiOk != true){
            btnYonetici.setBackground(new java.awt.Color(31,73,103));
            btnYonetici.setForeground(new java.awt.Color(10,25,74));
            isUserOk = false;
            isPersonelOk = false;
            isYoneticiOk = true;
            btnUser.setBackground(new java.awt.Color(10,25,74));
            btnUser.setForeground(new java.awt.Color(204,204,204));
            btnPersonel.setBackground(new java.awt.Color(10,25,74));
            btnPersonel.setForeground(new java.awt.Color(204,204,204));
            pnlUser.setVisible(false);
            pnlPersonel.setVisible(false);
            pnlYonetici.setVisible(true);
            
        }
    }//GEN-LAST:event_btnYoneticiMousePressed

    private void btnYoneticiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiMouseExited
        // TODO add your handling code here:
        if(isYoneticiOk==true){
            btnYonetici.setBackground(new java.awt.Color(204,204,204));
             btnYonetici.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnYonetici.setBackground(new java.awt.Color(10,25,74));
             btnYonetici.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnYoneticiMouseExited

    private void btnYoneticiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiMouseReleased
        // TODO add your handling code here:
        if(isYoneticiOk==true){
            btnYonetici.setBackground(new java.awt.Color(204,204,204));
             btnYonetici.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnYonetici.setBackground(new java.awt.Color(10,25,74));
             btnYonetici.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnYoneticiMouseReleased

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        pnlKayitOl.setVisible(true);
        pnlGirisYap.setVisible(false);
        this.setTitle("Kayıt Ol");
    }//GEN-LAST:event_jLabel6MousePressed
    boolean isUserKayitOk = true,isPersonelKayitOk = false,isYoneticiKayitOk = false;
    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        // TODO add your handling code here:
        if(isUserOk){
            i1 = new Musteri(txtUserNo.getText(),String.valueOf(txtUserParola.getPassword()),"Kullanıcı");
            if(i1.GirisYap()){
                
                mainUser n = new mainUser((Musteri)i1);
                n.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null,
    "Eksik veya hatalı giriş yapıldı. Lütfen bilgilerinizi kontrol ediniz.",
    "Giriş Yapılamadı",
    JOptionPane.ERROR_MESSAGE);
            }
        }
        if(isPersonelOk){
            i1 = new Personel(txtPersonelNo.getText(),String.valueOf(txtPersonelParola.getPassword()),"Personel");
            if(i1.GirisYap()){
                
                
                mainCalisan mn = new mainCalisan((Personel)i1);
                mn.setVisible(true);
                this.setVisible(false);
                
            }
            else{
                JOptionPane.showMessageDialog(null,
    "Eksik veya hatalı giriş yapıldı. Lütfen bilgilerinizi kontrol ediniz.",
    "Giriş Yapılamadı",
    JOptionPane.ERROR_MESSAGE);
            }
        }
        if(isYoneticiOk){
            i1 = new Yonetici(txtYoneticiNo.getText(),String.valueOf(txtYoneticiParola.getPassword()),"Yönetici");
            if(i1.GirisYap()){
                
                mainCalisan mn = new mainCalisan((Yonetici)i1);
                mn.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null,
    "Eksik veya hatalı giriş yapıldı. Lütfen bilgilerinizi kontrol ediniz.",
    "Giriş Yapılamadı",
    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void jLabel30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MousePressed
        // TODO add your handling code here:
        pnlGirisYap.setVisible(true);
        pnlSifremiUnuttum.setVisible(false);
        this.setTitle("Giriş Yap");
    }//GEN-LAST:event_jLabel30MousePressed

    private void btnUserLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLogin2ActionPerformed
        // TODO add your handling code here:
        String pType = "";
        if(isUserSifremiUnuttumOk) pType = "Kullanıcı";
        if(isPersonelSifremiUnuttumOk) pType = "Personel";
        if(isYoneticiSifremiUnuttumOk) pType = "Yönetici";
        if(Kullanici.SifremiUnuttum(txtSifremiUnuttum.getText(), pType).equals("")){
            JOptionPane.showMessageDialog(null,
    "Lütfen mail adresini ve kullanıcı tipini doğru seçtiğinizden emin olun.",
    "Kullanıcı Bulunamadı",
    JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null," Şifreniz : "+Kullanici.SifremiUnuttum(txtSifremiUnuttum.getText(), pType));
            txtSifremiUnuttum.setText("");
            pnlGirisYap.setVisible(true);
            pnlSifremiUnuttum.setVisible(false);
            this.setTitle("Giriş Yap");
        }
    }//GEN-LAST:event_btnUserLogin2ActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:[104,108,118]
        jLabel2.setForeground(new java.awt.Color(104,108,118));
        
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        jLabel2.setForeground(new java.awt.Color(255,255,255));
        pnlGirisYap.setVisible(false);
        pnlSifremiUnuttum.setVisible(true);
        pnlKayitOl.setVisible(false);
        pnlGirisYap.setVisible(true);
        pnlSifremiUnuttum.setVisible(false);
        pnlGirisYap.setVisible(false);
        pnlSifremiUnuttum.setVisible(true);
        this.setTitle("Şifremi Unuttum");
        
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        jLabel2.setForeground(new java.awt.Color(104,108,118));
    }//GEN-LAST:event_jLabel2MouseReleased
    boolean isUserSifremiUnuttumOk = true,isPersonelSifremiUnuttumOk =false, isYoneticiSifremiUnuttumOk = false;
    private void btnYoneticiSifremiUnuttumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiSifremiUnuttumMouseEntered
        // TODO add your handling code here:
        if(isYoneticiSifremiUnuttumOk== false){
             btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(51,35,119));
             btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
         }
    }//GEN-LAST:event_btnYoneticiSifremiUnuttumMouseEntered

    private void btnYoneticiSifremiUnuttumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiSifremiUnuttumMouseExited
        // TODO add your handling code here:
        if(isYoneticiSifremiUnuttumOk==true){
            btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(204,204,204));
             btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
             btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnYoneticiSifremiUnuttumMouseExited

    private void btnYoneticiSifremiUnuttumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiSifremiUnuttumMousePressed
        // TODO add your handling code here:
        if(isYoneticiSifremiUnuttumOk != true){
            btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(31,73,103));
            btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
            isUserSifremiUnuttumOk = false;
            isPersonelSifremiUnuttumOk = false;
            isYoneticiSifremiUnuttumOk = true;
            btnUserSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
            btnUserSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
            btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
            
        }
    }//GEN-LAST:event_btnYoneticiSifremiUnuttumMousePressed

    private void btnYoneticiSifremiUnuttumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiSifremiUnuttumMouseReleased
        // TODO add your handling code here:
        if(isYoneticiSifremiUnuttumOk==true){
            btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(204,204,204));
             btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
             btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnYoneticiSifremiUnuttumMouseReleased

    private void btnUserSifremiUnuttumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSifremiUnuttumMouseEntered
        // TODO add your handling code here:
        if(isUserSifremiUnuttumOk== false){
             btnUserSifremiUnuttum.setBackground(new java.awt.Color(51,35,119));
             btnUserSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
         }
    }//GEN-LAST:event_btnUserSifremiUnuttumMouseEntered

    private void btnUserSifremiUnuttumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSifremiUnuttumMouseExited
        // TODO add your handling code here:
        if(isUserSifremiUnuttumOk==true){
            btnUserSifremiUnuttum.setBackground(new java.awt.Color(204,204,204));
             btnUserSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnUserSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
             btnUserSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnUserSifremiUnuttumMouseExited

    private void btnUserSifremiUnuttumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSifremiUnuttumMousePressed
        // TODO add your handling code here:
        if(isUserSifremiUnuttumOk != true){
            btnUserSifremiUnuttum.setBackground(new java.awt.Color(31,73,103));
             btnUserSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
            isUserSifremiUnuttumOk = true;
            isPersonelSifremiUnuttumOk = false;
            isYoneticiSifremiUnuttumOk = false;
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
            btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
            btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
            btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
            
            
        }
    }//GEN-LAST:event_btnUserSifremiUnuttumMousePressed

    private void btnUserSifremiUnuttumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSifremiUnuttumMouseReleased
        // TODO add your handling code here:
        if(isUserSifremiUnuttumOk==true){
            btnUserSifremiUnuttum.setBackground(new java.awt.Color(204,204,204));
             btnUserSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnUserSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
             btnUserSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
        }
        
    }//GEN-LAST:event_btnUserSifremiUnuttumMouseReleased

    private void btnPersonelSifremiUnuttumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelSifremiUnuttumMouseEntered
        // TODO add your handling code here:
        if(isPersonelSifremiUnuttumOk== false){
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(51,35,119));
            btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnPersonelSifremiUnuttumMouseEntered

    private void btnPersonelSifremiUnuttumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelSifremiUnuttumMouseExited
        // TODO add your handling code here:
        if(isPersonelSifremiUnuttumOk==true){
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(204,204,204));
             btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
             btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnPersonelSifremiUnuttumMouseExited

    private void btnPersonelSifremiUnuttumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelSifremiUnuttumMousePressed
        // TODO add your handling code here:
        if(isPersonelSifremiUnuttumOk != true){
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(31,73,103));
            btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
            isUserSifremiUnuttumOk = false;
            isPersonelSifremiUnuttumOk = true;
            isYoneticiSifremiUnuttumOk = false;
            btnUserSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
            btnUserSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
            btnYoneticiSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
            btnYoneticiSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
            
            
        }
    }//GEN-LAST:event_btnPersonelSifremiUnuttumMousePressed

    private void btnPersonelSifremiUnuttumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelSifremiUnuttumMouseReleased
        // TODO add your handling code here:
        if(isPersonelSifremiUnuttumOk==true){
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(204,204,204));
             btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnPersonelSifremiUnuttum.setBackground(new java.awt.Color(10,25,74));
             btnPersonelSifremiUnuttum.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnPersonelSifremiUnuttumMouseReleased

    private void txtUserNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUserNoKeyTyped

    private void txtKayitTCKNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKayitTCKNMouseReleased
        // TODO add your handling code here:
        if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_txtKayitTCKNMouseReleased

    private void txtKayitYasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKayitYasMouseReleased
        // TODO add your handling code here:
        if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_txtKayitYasMouseReleased

    private void btnPersonelKayitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelKayitMouseReleased
        // TODO add your handling code here:
        if(isPersonelKayitOk==true){
            btnPersonelKayit.setBackground(new java.awt.Color(204,204,204));
            btnPersonelKayit.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnPersonelKayit.setBackground(new java.awt.Color(10,25,74));
            btnPersonelKayit.setForeground(new java.awt.Color(204,204,204));
        }
        if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_btnPersonelKayitMouseReleased

    private void btnPersonelKayitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelKayitMousePressed
        // TODO add your handling code here:
        if(isPersonelKayitOk != true){
            btnPersonelKayit.setBackground(new java.awt.Color(31,73,103));
            btnPersonelKayit.setForeground(new java.awt.Color(10,25,74));
            isUserKayitOk = false;
            isPersonelKayitOk = true;
            isYoneticiKayitOk = false;
            btnUserKayit.setBackground(new java.awt.Color(10,25,74));
            btnUserKayit.setForeground(new java.awt.Color(204,204,204));
            btnYoneticiKayit.setBackground(new java.awt.Color(10,25,74));
            btnYoneticiKayit.setForeground(new java.awt.Color(204,204,204));
            jLabel26.setText("Personel No");

        }
    }//GEN-LAST:event_btnPersonelKayitMousePressed

    private void btnPersonelKayitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelKayitMouseExited
        // TODO add your handling code here:
        if(isPersonelKayitOk==true){
            btnPersonelKayit.setBackground(new java.awt.Color(204,204,204));
            btnPersonelKayit.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnPersonelKayit.setBackground(new java.awt.Color(10,25,74));
            btnPersonelKayit.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnPersonelKayitMouseExited

    private void btnPersonelKayitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonelKayitMouseEntered
        // TODO add your handling code here:
        if(isPersonelKayitOk== false){
            btnPersonelKayit.setBackground(new java.awt.Color(51,35,119));
            btnPersonelKayit.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnPersonelKayitMouseEntered

    private void btnUserKayitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserKayitMouseReleased
        // TODO add your handling code here:
        if(isUserKayitOk==true){
            btnUserKayit.setBackground(new java.awt.Color(204,204,204));
            btnUserKayit.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnUserKayit.setBackground(new java.awt.Color(10,25,74));
            btnUserKayit.setForeground(new java.awt.Color(204,204,204));
        }
        if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_btnUserKayitMouseReleased

    private void btnUserKayitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserKayitMousePressed
        // TODO add your handling code here:
        if(isUserKayitOk != true){
            btnUserKayit.setBackground(new java.awt.Color(31,73,103));
            btnUserKayit.setForeground(new java.awt.Color(10,25,74));
            isUserKayitOk = true;
            isPersonelKayitOk = false;
            isYoneticiKayitOk = false;
            btnPersonelKayit.setBackground(new java.awt.Color(10,25,74));
            btnPersonelKayit.setForeground(new java.awt.Color(204,204,204));
            btnYoneticiKayit.setBackground(new java.awt.Color(10,25,74));
            btnYoneticiKayit.setForeground(new java.awt.Color(204,204,204));
            jLabel26.setText("Müşteri No");

        }
    }//GEN-LAST:event_btnUserKayitMousePressed

    private void btnUserKayitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserKayitMouseExited
        // TODO add your handling code here:
        if(isUserKayitOk==true){
            btnUserKayit.setBackground(new java.awt.Color(204,204,204));
            btnUserKayit.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnUserKayit.setBackground(new java.awt.Color(10,25,74));
            btnUserKayit.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnUserKayitMouseExited

    private void btnUserKayitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserKayitMouseEntered
        // TODO add your handling code here:
        if(isUserKayitOk== false){
            btnUserKayit.setBackground(new java.awt.Color(51,35,119));
            btnUserKayit.setForeground(new java.awt.Color(204,204,204));
        }

    }//GEN-LAST:event_btnUserKayitMouseEntered

    private void btnYoneticiKayitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiKayitMouseReleased
        // TODO add your handling code here:
        if(isYoneticiKayitOk==true){
            btnYoneticiKayit.setBackground(new java.awt.Color(204,204,204));
            btnYoneticiKayit.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnYoneticiKayit.setBackground(new java.awt.Color(10,25,74));
            btnYoneticiKayit.setForeground(new java.awt.Color(204,204,204));
        }
        if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_btnYoneticiKayitMouseReleased

    private void btnYoneticiKayitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiKayitMousePressed
        // TODO add your handling code here:
        if(isYoneticiKayitOk != true){
            btnYoneticiKayit.setBackground(new java.awt.Color(31,73,103));
            btnYoneticiKayit.setForeground(new java.awt.Color(10,25,74));
            isUserKayitOk = false;
            isPersonelKayitOk = false;
            isYoneticiKayitOk = true;
            btnUserKayit.setBackground(new java.awt.Color(10,25,74));
            btnUserKayit.setForeground(new java.awt.Color(204,204,204));
            btnPersonelKayit.setBackground(new java.awt.Color(10,25,74));
            btnPersonelKayit.setForeground(new java.awt.Color(204,204,204));
            jLabel26.setText("Yonetici No");
        }
    }//GEN-LAST:event_btnYoneticiKayitMousePressed

    private void btnYoneticiKayitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiKayitMouseExited
        // TODO add your handling code here:
        if(isYoneticiKayitOk==true){
            btnYoneticiKayit.setBackground(new java.awt.Color(204,204,204));
            btnYoneticiKayit.setForeground(new java.awt.Color(10,25,74));
        }
        else{
            btnYoneticiKayit.setBackground(new java.awt.Color(10,25,74));
            btnYoneticiKayit.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnYoneticiKayitMouseExited

    private void btnYoneticiKayitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoneticiKayitMouseEntered
        // TODO add your handling code here:
        if(isYoneticiKayitOk== false){
            btnYoneticiKayit.setBackground(new java.awt.Color(51,35,119));
            btnYoneticiKayit.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_btnYoneticiKayitMouseEntered

    private void btnKayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitOlActionPerformed
        // TODO add your handling code here:
        if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
        if(txtKayitAd.getText().isEmpty() || txtKayitSoyad.getText().isEmpty() || txtKayitYas.getText().isEmpty() || jComboBox1.getSelectedItem().toString().equals("Yıl")|| jComboBox2.getSelectedItem().toString().equals("Gün") || jComboBox3.getSelectedItem().toString().equals("Ay") || txtKayitTCKN.getText().isEmpty() || txtKayitTelefon.getText().isEmpty() || txtKayitMail.getText().isEmpty() || txtKayitKullanici.getText().isEmpty() || String.valueOf(txtKayitParola.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(null,
                "Lütfen tüm alanları eksiksiz bir şekilde doldurunuz. Kullanıcı No program tarafından tanımlanır.",
                "Kayıt Olunamadı",
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            String dogumTarihi = jComboBox2.getSelectedItem().toString() +"/" +jComboBox3.getSelectedItem().toString() +"/"+jComboBox1.getSelectedItem().toString();
            String cinsiyet = "";
            if(jRadioButton2.isSelected()) cinsiyet = "Erkek";
            else cinsiyet ="Kadın";
            String Ktype = "";
            if (isUserKayitOk) Ktype= "Kullanıcı";
            if(isPersonelKayitOk) Ktype= "Personel";
            if(isYoneticiKayitOk) Ktype= "Yönetici";
            i1 = new Kullanici(txtKayitKullanici.getText(),txtKayitAd.getText(),txtKayitSoyad.getText(),Integer.valueOf(txtKayitYas.getText()),dogumTarihi,txtKayitTCKN.getText(),txtKayitTelefon.getText(),cinsiyet,txtKayitMail.getText(),String.valueOf(txtKayitParola.getPassword()),Ktype);
            if(i1.KayitOl()){
                if (JOptionPane.showConfirmDialog(null, "Sistem tarafından sizlere oluşturulan Giriş ID'niz: "+txtKayitKullanici.getText() + "\nGiriş ID' si kopyalanarak devam edilsin mi?", "ID Kopyalansın mı?",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                String myString = txtKayitKullanici.getText();
                StringSelection stringSelection = new StringSelection(myString);
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                clipboard.setContents(stringSelection, null);
                JOptionPane.showMessageDialog(null, "Giriş Id'niz kopyalandı.");
                this.setTitle("Giriş Yap");
                // yes option
            } else {
                // no option
                this.setTitle("Giriş Yap");
            }

            txtKayitKullanici.setText("");
            txtKayitAd.setText("");
            txtKayitSoyad.setText("");
            txtKayitYas.setText("");
            txtKayitTCKN.setText("");
            txtKayitMail.setText("");
            txtKayitTelefon.setText("");
            txtKayitParola.setText("");
            jComboBox1.setSelectedIndex(0);
            jComboBox1.setSelectedIndex(0);
            jComboBox1.setSelectedIndex(0);
            pnlKayitOl.setVisible(false);
            pnlGirisYap.setVisible(true);
            pnlKayitOl.setVisible(false);
        }
            else{
                JOptionPane.showMessageDialog(null,
                "Kayıt olmada beklenmedik bir hata oluştu. Bu bilgilerle eşleşen bilgiler mevcut olabilir. Lütfen fakrlı giriş bilgileri deneyin.",
                "Kayıt Olunamadı",
                JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnKayitOlActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
        pnlKayitOl.setVisible(false);
        pnlGirisYap.setVisible(true);
        this.setTitle("Giriş Yap");
    }//GEN-LAST:event_jLabel13MousePressed

    private void txtKayitSoyadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKayitSoyadMouseReleased
        // TODO add your handling code here:
         if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_txtKayitSoyadMouseReleased

    private void txtKayitMailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKayitMailMouseReleased
        // TODO add your handling code here:
         if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_txtKayitMailMouseReleased

    private void txtKayitTelefonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKayitTelefonMouseReleased
        // TODO add your handling code here:
         if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_txtKayitTelefonMouseReleased

    private void txtKayitParolaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKayitParolaMouseReleased
        // TODO add your handling code here:
         if(txtKayitYas.getText().isEmpty() && txtKayitTCKN.getText().isEmpty()){
            txtKayitKullanici.setText("");
        }
        else{
            String firstPart = "";
            if (isUserKayitOk) firstPart = "101";
            if(isPersonelKayitOk) firstPart = "202";
            if(isYoneticiKayitOk) firstPart = "302";
            firstPart+=txtKayitYas.getText();
            firstPart+=txtKayitTCKN.getText().charAt(0);
            firstPart+=txtKayitTCKN.getText().charAt(1);
            firstPart+=txtKayitTCKN.getText().charAt(9);
            firstPart+=txtKayitTCKN.getText().charAt(10);
            txtKayitKullanici.setText(firstPart);
        }
    }//GEN-LAST:event_txtKayitParolaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKayitOl;
    private javax.swing.JLabel btnPersonel;
    private javax.swing.JLabel btnPersonelKayit;
    private javax.swing.JLabel btnPersonelSifremiUnuttum;
    private javax.swing.JLabel btnUser;
    private javax.swing.JLabel btnUserKayit;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JButton btnUserLogin2;
    private javax.swing.JLabel btnUserSifremiUnuttum;
    private javax.swing.JLabel btnYonetici;
    private javax.swing.JLabel btnYoneticiKayit;
    private javax.swing.JLabel btnYoneticiSifremiUnuttum;
    private javax.swing.ButtonGroup cinsiyet;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel pnlGirisYap;
    private javax.swing.JPanel pnlKayitOl;
    private javax.swing.JPanel pnlPersonel;
    private javax.swing.JPanel pnlSifremiUnuttum;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel pnlYonetici;
    private javax.swing.JTextField txtKayitAd;
    private javax.swing.JTextField txtKayitKullanici;
    private javax.swing.JTextField txtKayitMail;
    private javax.swing.JPasswordField txtKayitParola;
    private javax.swing.JTextField txtKayitSoyad;
    private javax.swing.JTextField txtKayitTCKN;
    private javax.swing.JTextField txtKayitTelefon;
    private javax.swing.JTextField txtKayitYas;
    private javax.swing.JTextField txtPersonelNo;
    private javax.swing.JPasswordField txtPersonelParola;
    private javax.swing.JTextField txtSifremiUnuttum;
    private javax.swing.JTextField txtUserNo;
    private javax.swing.JPasswordField txtUserParola;
    private javax.swing.JTextField txtYoneticiNo;
    private javax.swing.JPasswordField txtYoneticiParola;
    // End of variables declaration//GEN-END:variables
}
